name: Trigger Maven Tests

on:
  workflow_dispatch:

jobs:
  Para-Bank-Test:
      strategy:
          fail-fast: false
          max-parallel: 1
          matrix:
              test-tags:
                - @ParaBankRegistration

      uses: ./.github/workflows/maven-test.yml
      with:
        scenario-tag: ${{ matrix.test-tags}}
        step-def: "automation.parabank.steps"