name: Para Bank Tests
on:
  workflow_dispatch:

jobs:
  Para-Bank-Test:
      strategy:
          fail-fast: false
          max-parallel: 1
          matrix:
              test-tags:
                - ParaBankRegistration

      uses: ./.github/workflows/test-template.yml
      with:
        scenario-tag: ${{ matrix.test-tags}}
        step-def: "automation.parabank.steps"
